### ISSUE TITLE
Add requirements for `head.fontRevision`

### ISSUE THREAD

**Issue by be5invis** [openfv/openfv#3]
There's a field in the `head` which also indicates the font revision.
You may need to add requirements that this field should be synchronized with the Name ID.

**Comment by chrissimpkins** [comment]
Definition of head.fontRevision from [head — Font Header Table](https://www.microsoft.com/typography/otspec/head.htm)

| Type  |  Name  |  Description  |  
|:-:|---|---|
|   Fixed | fontRevision  | Set by font manufacturer. |

**Comment by chrissimpkins** [comment]
Additional data in this link that @moyogo sent to me:

http://silnrsi.github.io/FDBP/en-US/Versioning.html

Interesting comment there that I don't completely understand re: `head.majorVersion` `head.minorVersion`:

> The head table version numbers may be the only data that operating systems and installation routines use to compare multiple font versions and choose the most recent, so it is important that if two fonts have differences they should have different head table versions. These values can only be numbers.

My read of the OT spec is that `head.majorVersion` and `head.minorVersion` represent the version number of the head table spec, not of the font build.  The link in https://github.com/openfv/openfv/issues/3#issuecomment-354896216 states that `majorVersion` should be set to 1 and `minorVersion` should be set to 0.  While `head.fontRevision` is not specified beyond "Set by font manufacturer" this appears to be the head value that should change with changes in the nameID 5 records.

Anyone have additional information about this?

**Comment by kenlunde** [comment]
You are correct that _head.majorVersion_ and _head.minorVersion_ correspond to the 'head' table itself. What is important is the _head. fontRevision_ value, which should be synchronized with the _Font Version Number_ of the _name.ID=5 string. In fact, I believe that that the _head.fontRevision_ value represents the canonical version of the font resource.

**Comment by chrissimpkins** [comment]
Thanks @kenlunde.  Taking a look at how compilers are formatting `head.fontRevision` relative to nameID 5 version numbers.  Will post some additional info shortly.

**Comment by chrissimpkins** [comment]
Here is a sample from some fonts that I have on hand.  I did not include any metadata after a semicolon in the nameID 5 strings for fonts that include these data:

**Typeface**|**nameID 5**|**head.fontRevision**
:-----:|:-----:|:-----:
Menlo|8.0d2e1|2.028
DejaVu Sans Mono|Version 2.35|2.350
Source Code Pro|Version 1.017|1.017
Vialog|Version 1.00|1.000
Akzidenz Grotesk|Version 001.000|1.000
Avenir Next|Version 2.00|2.000
Linotype Didot|Version 1.01|1.001
Frutiger Neue|Version 2.000|2.000

It appears that `head.fontRevision` should have the format MAJOR.MINOR and include zero padding to three digits on the MINOR version.  Unclear what is going on with the Linotype Didot compile (nameID 5 = 1.01, head.fontRevision = 1.001) and the Menlo compile (nameID 5 = 8.0d2e1, head.fontRevision = 2.028).  Perhaps some post-compile version string modifications took place?

**Comment by chrissimpkins** [comment]
Some additional details related to Ken's comment in https://github.com/openfv/openfv/issues/3#issuecomment-354922370 from the footer of the Microsoft typography site, head table documentation:

> For historical reasons, the fontRevision value contained in this table is not used by Windows to determine the version of a font. Instead, Windows evaluates the version string (id 5) in the 'name' table.

**Comment by kenlunde** [comment]
I recommend that you get clarification from someone at Microsoft about that particular point.

**Comment by moyogo** [comment]
If I remember correctly, some fonts, like Apple's SF fonts, don't have matching head.fontRevision and nameID 5.

**Comment by chrissimpkins** [comment]
Added specification for head table fontRevision record in PR https://github.com/openfv/openfv/pull/8

**Comment by chrissimpkins** [comment]
> I recommend that you get clarification from someone at Microsoft about that particular point. 

@be5invis do you happen to have a contact at Microsoft?

> If I remember correctly, some fonts, like Apple's SF fonts, don't have matching head.fontRevision and nameID 5.

@moyogo This seems to be the case for Menlo too... https://github.com/openfv/openfv/issues/3#issuecomment-354924753 

Any idea what compiler they (Apple) use for their system fonts?

**Comment by chrissimpkins** [comment]
head.fontRevision specification merged as v0.2.0.  We can modify the language as you see fit based upon the text in the current document.  Thanks for pointing this issue out @be5invis !

**Comment by chrissimpkins** [comment]
Does anyone have information about use of `head.fontRevision` vs. `name.ID 5` to distinguish font versions on Apple and Linux systems?

**Comment by kenlunde** [comment]
On macOS, the Finder and the _Font Book_ app display the _name.ID=5_ string as the version of the font.

For our AFDKO tools, _makeotf_, which is our OpenType font compiler, builds the _name.ID=5_ string by first taking the _head.fontRevision_, which is specified as a 'head' table override in the "features" file. It then formats it as follows (taken from our latest OpenType/CFF Japanese font, _Ten Mincho_):

`Version 1.005;PS 1.005;hotconv 16.6.54;makeotf.lib2.5.65591`

I have no idea about Linux.

**Comment by chrissimpkins** [comment]
@kenlunde Thanks.  Interesting.  Unclear where/how head.fontRevision is being used out there.  It sounds like both Microsoft and Apple system software are using name.ID 5 as the default.

**Comment by be5invis** [comment]
For some of the fonts created by me, the head.fontRevision is first set as a float number, the rounded to a 16.16 fixed number. Then the NameID5 string is generated by a toFixed(3).

发自我的 iPhone

在 2018年1月4日，02:56，Chris Simpkins <notifications@github.com<mailto:notifications@github.com>> 写道：


@kenlunde<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenlunde&data=02%7C01%7C%7C7607a1534dd2406426dc08d552dbba47%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636506026024878232&sdata=Ysw5Bh47thiRXgoigRVcknwcqOZbUxSXddBBTWKCEDo%3D&reserved=0> Thanks. Interesting. Unclear where/how head.fontRevision is being used out there. It sounds like both Microsoft and Apple system software are using name.ID 5 as the default.

**Comment by kenlunde** [comment]
That doesn't surprise me, as it provides more information than _head.fontRevision_. BTW, and in case you were not aware, the `PS 1.005` portion of the _name.ID=5_ string represents the version number of the CFF (aka outlines). It is possible to revise an OpenType/CFF font in a way that does not change the CFF.

**Comment by chrissimpkins** [comment]
> For some of the fonts created by me, the head.fontRevision is first set as a float number, the rounded to a 16.16 fixed number. Then the NameID5 string is generated by a toFixed(3).

These are post-compilation changes or you have developed your own compiler?

**Comment by chrissimpkins** [comment]
> It is possible to revise an OpenType/CFF font in a way that does not change the CFF.

Another level of complexity.  @be5invis added this to his list of changes that warrant a version change in https://github.com/openfv/openfv/issues/4.  Out of interest, how do you use the dual versioning?  Is there a troubleshooting benefit to separation of the version numbers into two different version number strings?

**Comment by chrissimpkins** [comment]
> That doesn't surprise me, as it provides more information than head.fontRevision. 

Interested in whether systems use all of the information (beyond the version number) for things like font caching.  The routine use of a source state label in every build would address this for fonts that are versioned according to a release milestone.  If systems recognize only the version number, this approach does not work (at least not in an automated way with font caches) for display of builds across development to reach the release milestone.  I admittedly have little knowledge of font caching and no idea about implementation details but presumably it is built on parsing of one of these two records on all platforms.

**Comment by chrissimpkins** [comment]
Closing this thread as completed as the head.fontRevision record has been included in the specification.  Added outstanding issues from the thread to other pertinent open issue reports.  Please feel free to create new IR's for any other issues contained here that you would like to discuss further.
